### PR TITLE
fix(ts-error): add JSX.Element type option in addition to dep React.C…

### LINKED ISSUE #642: Bug Report - TypeScript error for renderRow, renderLeft/RightButton
# Describe the bug

```
  node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.d.ts:409:3
    409   renderRow?: (data: GooglePlaceData) => React.ComponentType<{}>;
          ~~~~~~~~~
    The expected type comes from property 'renderRow' which is declared here on type 'IntrinsicAttributes & GooglePlacesAutocompleteProps & RefAttributes<GooglePlacesAutocompleteRef>'
```

a similar error manifests for all three renderRow renderLeftButton renderRightButton.

```
src/routes/LiveUserProfile/LiveUserLocationModal/index.tsx:200:21 - error TS2322: Type '() => JSX.Element' is not assignable to type '() => ComponentType<{}>'.
  Type 'Element' is not assignable to type 'ComponentType<{}>'.
    Type 'Element' is not assignable to type 'FunctionComponent<{}>'.
      Type 'Element' provides no match for the signature '(props: { children?: ReactNode; }, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null'.

200                     renderLeftButton={() => {
                        ~~~~~~~~~~~~~~~~

  node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.d.ts:407:3
    407   renderLeftButton?: () => React.ComponentType<{}>;
          ~~~~~~~~~~~~~~~~
    The expected type comes from property 'renderLeftButton' which is declared here on type 'IntrinsicAttributes & GooglePlacesAutocompleteProps & RefAttributes<GooglePlacesAutocompleteRef>'

src/routes/LiveUserProfile/LiveUserLocationModal/index.tsx:208:21 - error TS2322: Type '() => JSX.Element' is not assignable to type '() => ComponentType<{}>'.
  Type 'Element' is not assignable to type 'ComponentType<{}>'.
    Type 'Element' is not assignable to type 'FunctionComponent<{}>'.

208                     renderRightButton={() => {
                        ~~~~~~~~~~~~~~~~~

  node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.d.ts:408:3
    408   renderRightButton?: () => React.ComponentType<{}>;
          ~~~~~~~~~~~~~~~~~
    The expected type comes from property 'renderRightButton' which is declared here on type 'IntrinsicAttributes & GooglePlacesAutocompleteProps & RefAttributes<GooglePlacesAutocompleteRef>'

src/routes/LiveUserProfile/LiveUserLocationModal/index.tsx:224:21 - error TS2322: Type '(results: GooglePlaceData) => Element' is not assignable to type '(data: GooglePlaceData) => ComponentType<{}>'.
  Type 'Element' is not assignable to type 'ComponentType<{}>'.
    Type 'Element' is not assignable to type 'FunctionComponent<{}>'.

224                     renderRow={(results): JSX.Element => {
                        ~~~~~~~~~
```
# Reproduction - (required - issue will be closed without this)

Steps to reproduce the behavior - a minimal reproducible code example, link to a [snack](https://snack.expo.io) or a repository.

**Please provide a FULLY REPRODUCIBLE example.**

<details>
  <summary>Click to expand!</summary>
  
  ```javascript
     <GooglePlacesAutocomplete
                    renderLeftButton={() => {
                      return (
                        <SVGIcon
                          icon={icons.search.searchMagnifyingGlass}
                          style={styles.searchIcon}
                        />
                      );
                    }}
                    renderRightButton={() => {
                      return (
                        <>
                          <TouchableOpacity
                            onPress={(): void => {
                              onDismissModal(false);
                            }}
                          >
                            <Text style={styles.cancelText}>
                              {locales.cancel}
                            </Text>
                          </TouchableOpacity>
                        </>
                      );
                    }}
                    renderRow={(results): JSX.Element => {
                      return (
                        <View style={styles.resultsContainer}>
                          <TouchableOpacity
                            onPress={(): void => {
                              setLocation(results.description);
                            }}
                          >
                            <View style={styles.resultsRow}>
                              <Text style={styles.resultsText}>
                                {results.description}
                              </Text>
                              <SVGIcon
                                icon={icons.search.caretOut}
                              />
                            </View>
                          </TouchableOpacity>
                        </View>
                      );
                    }}
                    query={{
                      components: 'country:us',
                      key: 'myApiKey',
                      language: 'en',
                      types: '(cities)',
                    }}
                  />
    
  ```
</details>

_Please remember to remove you google API key from the code you provide here_

# Additional context

Obviously this appears to be a TS issue. 

Looking here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts

I see this:

```
    type ElementType<P = any> =
        {
            [K in keyof JSX.IntrinsicElements]: P extends JSX.IntrinsicElements[K] ? K : never
        }[keyof JSX.IntrinsicElements] |
        ComponentType<P>;
    /**
     * @deprecated Please use `ElementType`
     */
    type ReactType<P = any> = ElementType<P>;
    type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>;

```

- Library Version: 2.0.3
- React Native Version: 0.61.5
- TypeScript Version: 3.8.2

- [ ] iOS
- [ ] Android
- [ ] Web

If you are using expo please indicate here:

- [ ] I am using expo

Add any other context about the problem here, screenshots etc

### PR DESCRIPTION
**Pull request by rgordon95**
fix componentType by adding option for JSX.Element on renderRow/LeftButton/Header etc.

should replace ComponentType with ElementType in future but did not fix for me

should fix #642

### CODE REVIEW

**Comment by rgordon95** [comment]
any chance we can push this through? @bell-steven

**Comment by rgordon95** [comment]
There were also type errors when referencing an object instead of directly inline passing the object. I have added a fix for this in the second commit.

**Comment by dspencer926** [comment]
This change would be very helpful!  @bell-steven please merge this when you get a chance

**Comment by bell-steven** [comment]
Thank you @rgordon95.  I will get to this as soon as I have a chance.

File: GooglePlacesAutocomplete.d.ts [hunk 1]
```diff
@@ -401,19 +401,20 @@ interface GooglePlacesAutocompleteProps {
...
+  query: Query | Object;
   renderDescription?: (description: DescriptionRow) => string;
-  renderHeaderComponent?: () => React.ComponentType<{}>;
-  renderLeftButton?: () => React.ComponentType<{}>;
-  renderRightButton?: () => React.ComponentType<{}>;
-  renderRow?: (data: GooglePlaceData) => React.ComponentType<{}>;
+  renderHeaderComponent?: () => JSX.Element | React.ComponentType<{}>;
+  renderLeftButton?: () => JSX.Element | React.ComponentType<{}>;
+  renderRightButton?: () => JSX.Element | React.ComponentType<{}>;
+  renderRow?: (data: GooglePlaceData) => JSX.Element | React.ComponentType<{}>;
```
Comment (rmessenger) [inline GooglePlacesAutocomplete.d.ts:409]:
```suggestion
  renderHeaderComponent?: () => JSX.Element;
  renderLeftButton?: () => JSX.Element;
  renderRightButton?: () => JSX.Element;
  renderRow?: (data: GooglePlaceData) => JSX.Element;
```

Correct me if I'm wrong, but the way these are being used in the code (snippet below), I don't think a `ComponentType` can go here.

image

File: GooglePlacesAutocomplete.d.ts [hunk 2]
```diff
@@ -401,19 +401,20 @@ interface GooglePlacesAutocompleteProps {
...
+  
   // sets the request URL to something other than the google api.  Helpful if you want web support or to use your own api.
   requestUrl?: RequestUrl;
-  styles?: Partial<Styles>;
+  styles?: Partial<Styles> | Object;
```
Comment (rmessenger) [inline GooglePlacesAutocomplete.d.ts:413]: Why is this necessary?

**Comment by rmessenger** [comment]
I would love to see this fixed. This is such a great library, and having accurate type defs would be awesome! :+1:

**Comment by bell-steven** [comment]
@rmessenger  I have basically no experience with typescript, so I can't give an opinion here. 
@rgordon95 can you address these points?

File: GooglePlacesAutocomplete.d.ts (hunk 1 above)
Comment (rgordon95) [reply GooglePlacesAutocomplete.d.ts:409]: You are right. it is deprecated and why I added an or conditional to allow passing checks. this will need further modification but i dont fully understand why it was implemented the way it was originally and simply wished to improve it  to a point it was usable within our project. 

I can update the PR to only use JSX.Element however I was hoping to avoid breaking changes for anyone who solved for the old typedefs already.

File: GooglePlacesAutocomplete.d.ts (hunk 2 above)
Comment (rgordon95) [reply GooglePlacesAutocomplete.d.ts:413]: TS complained when passing an object into the styles prop if it was not inline.

File: GooglePlacesAutocomplete.d.ts (hunk 1 above)
Comment (bell-steven) [reply GooglePlacesAutocomplete.d.ts:409]: These typedefs were originally written a very long time ago. I am fine with it "just working" for now. Let's fix the deprecation in a separate PR, and keep the breaking changes there.

File: GooglePlacesAutocomplete.d.ts (hunk 2 above)
Comment (yoshiwarab) [reply GooglePlacesAutocomplete.d.ts:413]: This (and all the other "| Object" fields) allows any object to be passed as style, effectively breaking type checking. @rgordon95 I have had no issue passing in a non-inlined styles prop, and can't see a reason why doing so might have cause a typescript error unless the object passed was not of the correct type.
